### ISSUE TITLE
prevent user from exiting a route on a certain condition (Eg. if typing something)

### ISSUE THREAD

**Issue by geekyme** [iron-meteor/iron-router#553] opened 2014-03-29 06:16 UTC
hello, 

I'm trying to implement the follow use case on my app: 
if the user is typing something in a textbox and he navigates away from the current page, I want to be able to produce a confirm box (cancel / ok) to intercept the navigation. 

I tried to do this in the current onStop hook : 

<pre>
if(Session.get('typing')){
        if(confirm('Are you sure you want to leave? Your text will be gone.')){
          Session.set('typing', false)
        }else{
          this.stop();
          return;
        }
      }
</pre>

I get some kind of maximum call stack error if i do this. Is there other ways ?

**Comment by hellogerard** [comment] 2015-04-06 17:27
I'd close this as a dupe of #698

**Comment by lance-anderson** [comment] 2015-07-06 21:24
+1 

I have the same use case as described above. I'm wanting to prompt the user if they have unsaved changes. I'm using ```window.onbeforeunload``` to catch users leaving my app. I tried using the Router.go override however that didn't catch in-app links and button clicks etc. What worked in the end was a solution I found on SO:

```
var originalDispatch = Router.dispatch;

Router.dispatch = function() {
  if (!Session.get('isDirty') || confirm('Are you sure?')) {
    Session.set('isDirty', false);
    originalDispatch.apply(this, arguments);
  }
}
```

**Comment by Siyfion** [comment] 2015-09-11 09:28
@tmeasday I tried your work-around but it didn't seem to do anything... Is there no accepted solution to this at the moment? @cmather You said you were willing to help figure out how to do it; am I missing something?

**Closed** 2017-06-30 19:09 UTC
Labels: contribute, enhancement

**Comment by MohammedEssehemy** [comment] 2018-03-02 15:07
@Siyfion 
for url change check [this comment](https://github.com/iron-meteor/iron-router/issues/698#issuecomment-312350115)
