### ISSUE TITLE
onBeforeAction is not onBefore when using layoutTemplates

### ISSUE THREAD

**Issue by satyavh** [iron-meteor/iron-router#1256] opened 2015-02-28 10:07 UTC
It turns out that the `onBeforeAction` is not really onBefore when using `layoutTemplate` or `this.layout`. Iron Router still renders the layout template before checking the onBefore conditions, which is potentially a security thread. 

Here's an example:

Create the following route and onBeforeAction

```
@route 'someRoute',
  path: '/someroute'
  template: 'someRoute'
  layoutTemplate: 'myTemplate'
@route 'login',
  template: 'login'
  path: 'login'

checkUserLoggedIn = ->
  if not Meteor.user() and not Meteor.loggingIn()
     Router.go '/login'
  else
     @next()

Router.onBeforeAction checkUserLoggedIn
```

what will happen if you go to `/someroute` without being logged in, the layoutTemplate will briefly show before the onBeforeAction kicks in and redirects you to `/login`. Which means the not logged-in user can still see parts of the application that he's really not supposed to.

**This is a security threat!**

## How to solve
To only way I could find to solve this, is by applying the layout via an action, like this:

```
@route 'someRoute',
  path: '/someroute'
  action: ->
    if Meteor.user()
      @layout  'myTemplate'
      @render 'someRoute'
```

which basically renders your onBefore check useless. This bug also makes it impossible to set a generic layoutTemplate for all or a set of routes, resulting in a lot of repetitive code.

It also makes me wonder how 'onBefore' the 'onBeforeAction' actually is. At least when using layoutTemplates, it really doesn't seem to execute before the route.

**Comment by ramsaylanier** [comment] 2015-02-28 17:51
Dont you need to specify a loading template?

**Comment by VladShcherbin** [comment] 2015-03-06 10:50
+1

**Comment by jhuenges** [comment] 2015-03-06 11:59
:+1:

**Comment by lucatros** [comment] 2015-03-08 23:21
+1

**Comment by vladblindu** [comment] 2015-03-17 10:15
+1

**Comment by jhuenges** [comment] 2015-03-17 14:17
@cmather do you have any suggestions?

**Comment by cmather** [comment] 2015-03-17 15:21
Sorry guys will post later today.

**Comment by vladblindu** [comment] 2015-03-17 15:36
I am quite a noob and iron-router's "mechanics" is way beyond my coding skills, but I feel that somehow
onBeforeAction should be really "before". I don't exactly understand where the layout is getting rendered but probably having it render after onBeforeAction and before "action" would be the best option.
Again, I's a wish not a suggestion.

**Comment by cmather** [comment] 2015-03-17 22:30
Hey everyone. So a couple of thoughts here. First, you can check out precisely what's happening by looking at lib/route_controller_client.js: https://github.com/iron-meteor/iron-router/blob/devel/lib/route_controller_client.js#L108.

If you skim down to line 185 you'll notice that `this.layout(this.lookupOption('layoutTemplate'))` is called which is what sets the default layout for the page.

Then, a little further down on line 229 you'll see the before hooks being collected and then finally the process kicking off on line 241. The hooks and action function are indeed called after the default layout call above (otherwise how would we tell whether to use the default layout vs. going with what the user set in the action or hook?). However, all of this is run in the **same computation**. The rendering gets flushed at all once after this cycle completes which means the last layout to get set will win and be rendered to the page (until the computation is rerun at a later time).

So what does this mean. It's possible the default layout gets set until some reactive condition is true, like your user logs in. But if you set a layout in one of your hooks or your action function it will definitely override the default layout every time. What I've done in the past is account for the various stages of logging in and have a layout or template for each state. So you have (1) not logged in; (2) logging in; and (3) logged in. You can avoid showing the logged in layout by setting a not logged in layout by default, and changing it once the logged in state changes. Make sense?

Also, it's important to note that this is a usability issue and **NOT A SECURITY THREAT**. Ultimately, the client is not secure at all (anyone can open a js console and do what they want). The ultimate authority for security is the server. But nonetheless, no point in showing the user an interface they can't do anything with.

**Comment by cmather** [comment] 2015-03-17 22:31
Closing issue but of course we can continue to discuss!

**Closed by cmather** 2015-03-17 22:31 UTC

**Comment by lucatros** [comment] 2015-03-17 22:34
Good point. Thanks for the explanation and the suggested workaround.

**Comment by cmather** [comment] 2015-03-17 22:39
Sure!

**Comment by VladShcherbin** [comment] 2015-03-18 12:23
@cmather with all the respect, the before filter should run before everything, this is why it is called *before*.

now, the default layout is **created and rendered** before the **before** action. this is not right in any way.

you should seriously consider changing this confusing behaviour.

**Comment by cmather** [comment] 2015-03-18 16:55
Hi @VladShcherbin, I can see what you're observing - the wrong layout being rendered - but it's not related to the order of the before filter vs. default layout. It's related to the current state at the time the functions run. In other words, in the first example at the very top of this issue, on the first pass `!Meteor.user() && !Meteor.loggingIn()` is `false`. So, even if we put the default layout method call at the end, it wouldn't make a difference. Let me try to expand on my explanation above since admittedly this is a pretty confusing topic.

Let's drop into iron:layout directly so you can see what's happening.

```javascript
layout = new Iron.Layout();
layout.insert({el: '#container'});

// let's say we set the layout template to the 'LoggedInLayout' like so...
layout.template('LoggedInLayout');

// then in the second line we set it to another layout...
layout.template('NotLoggedInLayout');

// which templates get rendered to the page?
```

Which templates get rendered to the page? Only the 'NotLoggedInLayout'. The reason is that both of these rendered calls are not executed right away (if for some reason you're seeing that behavior because of some change Meteor made let me know). The calls are queued up and "flushed" later. So the last one in will win.

Now let's take it a step further and put these calls into a reactive computation to illustrate the issue you're probably seeing.

```javascript
// anything reactive function calls in this callback could cause the function
// to RUN AGAIN.
Tracker.autorun(function(computation) {
  // set a default layout
  layout.template('LoggedInLayout');

  // okay now check if the user is logged in. ON FIRST RUN THIS WILL NOT
  // BE TRUE BECAUSE the login process hasn't started yet. Remember it's
  // async.
  if (!Meteor.user() && !Meteor.loggingIn()) {
    layout.template('NotLoggedInLayout');
  }
});
```

So to fix this, you can set the default layout to the not logged in layout.

```javascript
Tracker.autorun(function(computation) {
  layout.template('NotLoggedInLayout');
  if (Meteor.user()) layout.template('LoggedInLayout');
});
```

Happy to follow up if any of the above is not clear, or if you're seeing a different behavior.

**Comment by VladShcherbin** [comment] 2015-03-19 07:43
@cmather Hi, I've created an example of what is confusing me and the others

http://ir-layout-template.meteor.com/

You are not logged in, but if you go to [http://ir-layout-template.meteor.com/admin](http://ir-layout-template.meteor.com/admin), you will see for a second the **layoutTemplate** of the [AdminController](https://github.com/VladShcherbin/ir-layout-template/blob/master/client/views/admin/layout/lib/router/router.js).

The example repository: https://github.com/VladShcherbin/ir-layout-template/

How can we solve this?

**Comment by cmather** [comment] 2015-03-20 01:37
Hey @VladShcherbin, I'm trying to trace through this app but there's a lot of dependencies and I've run out of time. Can you create a simple app with 3 files illustrating the issue with as few dependencies and code paths as possible? If you do that I'll submit a pull request showing how to fix the issue.

**Comment by VladShcherbin** [comment] 2015-03-20 08:16
@cmather hi. sure, I`ve simplified the code to 3 files, [here you are](https://github.com/VladShcherbin/ir-layout-template)

**Comment by cmather** [comment] 2015-03-20 16:53
Hi @VladShcherbin, Thanks! That made it much easier to reason about. I forked the repository and added a few things to determine if the admin layout was indeed rendering for users not logged in. I determined it wasn't. See comment on the PR I submitted to your repo: https://github.com/VladShcherbin/ir-layout-template/pull/1. Let me know if you're seeing something different.

**Comment by VladShcherbin** [comment] 2015-03-20 17:16
@cmather Hi, I`ve updated the repository and website - the issue is still there. The admin layout is shown if you go straight to [ir-layout-template.meteor.com/admin](ir-layout-template.meteor.com/admin) page, not from the main one. It shows the adminLayout for a second and not every time.

Here is the video -> [link](https://www.dropbox.com/s/d514fdnd2jo63gf/ir-layout-template.mov?dl=0), first time I go to `/admin`, it does not show, second time it does.

**Comment by VladShcherbin** [comment] 2015-03-20 17:20
@cmather you can see an area with a teal background and admin template for a second. the **created** and **rendered** are not fired, so there is nothing in the console. But we can see it. 

How is that possible?

**Comment by VladShcherbin** [comment] 2015-03-20 17:28
@cmather okay, I`ve tested for **created** console log, and it does show. I add this to repository to [repository](https://github.com/VladShcherbin/ir-layout-template/commit/938e03c10934844adb40033c760686d99ac37509) and update the website.

Go straight to [http://ir-layout-template.meteor.com/admin](http://ir-layout-template.meteor.com/admin) and you can see the console message.

**Comment by cmather** [comment] 2015-03-20 17:58
Ok I'll come back and take another look this afternoon.

**Comment by cmather** [comment] 2015-03-21 00:02
Hi @VladShcherbin

**Comment by cmather** [comment] 2015-03-21 00:06
I do see that the created event callback is called, even though the template doesn't seem to be rendering. I need to double check why that is.

**Comment by cmather** [comment] 2015-03-21 00:07
I wonder if it's some kind of flushing issue. What browser are you using?

**Comment by VladShcherbin** [comment] 2015-03-21 01:22
@cmather Hi, I'm using Mac os and Chrome 43.0.2 canary. The template is also created and created log is added to the console in Chrome 39.0.2, Safari 8.0.5, Firefox 34.0.5, Opera 12.16.

**Comment by jhuenges** [comment] 2015-03-21 18:52
Same with Win7 and Chrome 41.0

**Comment by theduke** [comment] 2015-03-26 13:13
I have a problem with this that goes in a different direction.
I need the ability to prevent a route change in a hook, so I can do this.stop() and the page just stays the way it is.

Currently I can't do this, because the layout will render and replace the current route.

**Comment by VladShcherbin** [comment] 2015-03-27 16:38
@cmather Hi, any news or solution for this problem ?

**Comment by cmather** [comment] 2015-03-27 18:25
Sorry got swept into other stuff. For now I would assume the user login process doesn't start right away. So don't do a redirect and instead show a template for not logged in users first, then set to the admin layout after login completes.

**Comment by rogchap** [comment] 2015-07-07 01:14
I'm also having the same issue... It's not noticeable during development, but as soon as I publish to production I get a "flash" of the admin template before it redirects to the log in page.

Although this is not a fix, I solved the problem by implementing MeteorHack's fast-render: https://github.com/meteorhacks/fast-render

Hope this might help some people.
