### ISSUE TITLE
How to abort move to another page with onStop?

### ISSUE THREAD

**Issue by hiphapis** [iron-meteor/iron-router#1195] opened 2015-01-26 08:01 UTC
Using `onStop` I can intercept the router before a page transition. Is it possible to abort the page transition? I have tried returning `true` / `false` and calling `this.stop()` but nothing seems to work. Any help would be much appreciated.

**Comment by mpranjic** [comment] 2015-02-14 22:59
You can't. See #698

**Comment by hiphapis** [comment] 2015-03-19 05:10
@mpranjic Thanks! :cry:

**Comment by JamesLefrere** [comment] 2015-03-25 17:14
@hiphapis How about https://github.com/ephemer/meteor-before-leave-previous ? I haven't tried it myself, but it could work...

**Comment by hellogerard** [comment] 2015-04-06 17:27
I'd close this as a dupe of #698

**Closed** 2017-06-30 17:13 UTC
